[mongodb]
mongodb-dev.jyothiy.online

[catalogue]
catalogue-dev.jyothiy.online

[redis]
redis-dev.jyothiy.online

[cart]
cart-dev.jyothiy.online

[user]
user-dev.jyothiy.online

[all:vars]
ansible_user=ec2-user
ansible_password=DevOps321
MONGODB_HOST=mongodb-dev.jyothiy.online
CATALOGUE_HOST=catalogue-dev.jyothiy.online
REDIS_HOST=redis-dev.jyothiy.online
USER_HOST=user-dev.jyothiy.online


