- name: create a ec2 and r54 records
  hosts: all
  connection: local
  vars:
    sg_id: sg-0b983c3e1d2cd0e5c
    ami_id: ami-0220d79f3f480ecf5
    envr: dev
    instances: 
       - mongodb
       - catalogue
  tasks:
   - name: create ec2 instance
     amazon.aws.ec2_instance:
       instance_type: "t3.micro"
       security_group: "{{ sg_id }}"
       image_id: "{{ ami_id }}"
       name: "{{ item }}-{{ envr }}"
       tags:
         - Project: roboshop
           Component: "{{ item }}"
           Environment: "{{ envr }}"
           Name: "{{ item }}-{{ envr }}"
     loop: "{{ instances }}"
     register: ec2_output

   - name: print the output
     ansible.builtin.debug:
       msg: "{{ ec2_output }}"